server:
  port: 8084

spring:
  application:
    name: order-service  # 改回来，不是 coupon-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: localhost:8858

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

seata:
  enabled: true
  tx-service-group: shopcoupon-tx-group
  service:
    vgroup-mapping:
      shopcoupon-tx-group: default
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      namespace: ""
      group: SEATA_GROUP
      application: seata-server