server:
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/redis_heima?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

seata:
  enabled: true
  tx-service-group: shopcoupon-tx-group
  service:
    vgroup-mapping:
      shopcoupon-tx-group: default
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      group: SEATA_GROUP
      application: seata-server
  data-source-proxy-mode: AT

feign:
  sentinel:
    enabled: true
